apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::696919879899:role/eksctl-abn-nodegroup-abn-NodeInstanceRole-D377VD1CVu4u
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - abn-pod-reader
      userarn: arn:aws:iam::650732254329:user/sandeep
      username: sandeep     
kind: ConfigMap
metadata:
  creationTimestamp: "2025-04-09T06:09:20Z"
  name: aws-auth
  namespace: kube-system
  uid: ac59db96-9e9c-4a66-b1c7-7420c5415841
