apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::696919879899:role/eksctl-abn-nodegroup-abn-NodeInstanceRole-D377VD1CVu4u
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - abn-pod-reader
      userarn: arn:aws:iam::696919879899:user/sandeep      
      username: sandeep
    - groups:
      - abn-pod-reader
      userarn: arn:aws:iam::696919879899:user/vaishu      
      username: vaishu       
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-26T05:04:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1170"
  uid: ac59db96-9e9c-4a66-b1c7-7420c5415841


#userarn: arn:aws:iam::696919879899:user/sandeep copy it from from sandeep iAM userdetails arn okay 
